[jupyter] update tutorials link
v3io/helm-charts pull request #981
Opened 2023-06-27 12:25 UTC by daniels290813

### Checklist

[Place an '[x]' (no spaces) in all applicable fields. Please remove irrelevant fields.]

- [ ] Chart Version bumped
- [ ] Title of the PR starts with chart name (e.g. `[mychartname]`)

### Description

[Please add a description of the change request.]

2023-06-27 12:41 UTC, alexpirogovski approved these changes

2023-06-27 16:19 UTC, liranbg requested changes
Must have a way to make this change backwards compatible with older iguazio versions

2023-06-28 02:25 UTC, daniels290813 commented
@liranbg new code is compatible with older iguazio versions - can handle both tutorial sources

2023-06-28 03:08 UTC, liranbg approved these changes

2023-06-28 05:48 UTC, daniels290813 commented
@alexpirogovski @liranbg you guys can merge/approve workflow ?

2023-06-28 11:44 UTC, merged